version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    environment:
      DB_HOST: db
      DB_DATABASE: 'more_corp'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'pass'
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'more_corp'
      MYSQL_ROOT: 'root'
      MYSQL_ROOT_PASSWORD: 'pass'
    volumes:
      - ./storage/dbdata:/var/lib/mysql
