version: "3.7"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: more_corp
      DB_USERNAME: root
      DB_PASSWORD:
    ports:
      - 8000:8000
    volumes:
      - ./api:/app/api
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - api

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "more_corp"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
